spring.application.name=LoadBalancerGateway

server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=load_balanced_route
spring.cloud.gateway.server.webflux.routes[0].uri=https://example.org
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/loadbalanced/**