spring.application.name=ResilienceGateway

server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=resilience_route
spring.cloud.gateway.server.webflux.routes[0].uri=https://example.org
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/resilience/**

resilience4j.circuitbreaker.instances.exampleCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.failureRateThreshold=50
